# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: PbCsv.pb
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='PbCsv.pb',
  package='pbCsv',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x08PbCsv.pb\x12\x05pbCsv\">\n\x05PbCsv\x12\x12\n\nheaderList\x18\x06 \x03(\t\x12!\n\ncolumnList\x18\x05 \x03(\x0b\x32\r.pbCsv.Column\"j\n\x06\x43olumn\x12)\n\x0b\x63olumnFloat\x18\x03 \x01(\x0b\x32\x12.pbCsv.ColumnFloatH\x00\x12%\n\tcolumnInt\x18\x04 \x01(\x0b\x32\x10.pbCsv.ColumnIntH\x00\x42\x0e\n\x0c\x63olumn_typed\" \n\x0b\x43olumnFloat\x12\x11\n\tvalueList\x18\x01 \x03(\x02\"\x1e\n\tColumnInt\x12\x11\n\tvalueList\x18\x02 \x03(\x05'
)




_PBCSV = _descriptor.Descriptor(
  name='PbCsv',
  full_name='pbCsv.PbCsv',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='headerList', full_name='pbCsv.PbCsv.headerList', index=0,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='columnList', full_name='pbCsv.PbCsv.columnList', index=1,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=81,
)


_COLUMN = _descriptor.Descriptor(
  name='Column',
  full_name='pbCsv.Column',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='columnFloat', full_name='pbCsv.Column.columnFloat', index=0,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='columnInt', full_name='pbCsv.Column.columnInt', index=1,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='column_typed', full_name='pbCsv.Column.column_typed',
      index=0, containing_type=None,
      create_key=_descriptor._internal_create_key,
    fields=[]),
  ],
  serialized_start=83,
  serialized_end=189,
)


_COLUMNFLOAT = _descriptor.Descriptor(
  name='ColumnFloat',
  full_name='pbCsv.ColumnFloat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='valueList', full_name='pbCsv.ColumnFloat.valueList', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=223,
)


_COLUMNINT = _descriptor.Descriptor(
  name='ColumnInt',
  full_name='pbCsv.ColumnInt',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='valueList', full_name='pbCsv.ColumnInt.valueList', index=0,
      number=2, type=5, cpp_type=1, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=225,
  serialized_end=255,
)

_PBCSV.fields_by_name['columnList'].message_type = _COLUMN
_COLUMN.fields_by_name['columnFloat'].message_type = _COLUMNFLOAT
_COLUMN.fields_by_name['columnInt'].message_type = _COLUMNINT
_COLUMN.oneofs_by_name['column_typed'].fields.append(
  _COLUMN.fields_by_name['columnFloat'])
_COLUMN.fields_by_name['columnFloat'].containing_oneof = _COLUMN.oneofs_by_name['column_typed']
_COLUMN.oneofs_by_name['column_typed'].fields.append(
  _COLUMN.fields_by_name['columnInt'])
_COLUMN.fields_by_name['columnInt'].containing_oneof = _COLUMN.oneofs_by_name['column_typed']
DESCRIPTOR.message_types_by_name['PbCsv'] = _PBCSV
DESCRIPTOR.message_types_by_name['Column'] = _COLUMN
DESCRIPTOR.message_types_by_name['ColumnFloat'] = _COLUMNFLOAT
DESCRIPTOR.message_types_by_name['ColumnInt'] = _COLUMNINT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PbCsv = _reflection.GeneratedProtocolMessageType('PbCsv', (_message.Message,), {
  'DESCRIPTOR' : _PBCSV,
  '__module__' : 'PbCsv.pb_pb2'
  # @@protoc_insertion_point(class_scope:pbCsv.PbCsv)
  })
_sym_db.RegisterMessage(PbCsv)

Column = _reflection.GeneratedProtocolMessageType('Column', (_message.Message,), {
  'DESCRIPTOR' : _COLUMN,
  '__module__' : 'PbCsv.pb_pb2'
  # @@protoc_insertion_point(class_scope:pbCsv.Column)
  })
_sym_db.RegisterMessage(Column)

ColumnFloat = _reflection.GeneratedProtocolMessageType('ColumnFloat', (_message.Message,), {
  'DESCRIPTOR' : _COLUMNFLOAT,
  '__module__' : 'PbCsv.pb_pb2'
  # @@protoc_insertion_point(class_scope:pbCsv.ColumnFloat)
  })
_sym_db.RegisterMessage(ColumnFloat)

ColumnInt = _reflection.GeneratedProtocolMessageType('ColumnInt', (_message.Message,), {
  'DESCRIPTOR' : _COLUMNINT,
  '__module__' : 'PbCsv.pb_pb2'
  # @@protoc_insertion_point(class_scope:pbCsv.ColumnInt)
  })
_sym_db.RegisterMessage(ColumnInt)


# @@protoc_insertion_point(module_scope)
