# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: static/protoDefs/PbCurveList.pb
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='static/protoDefs/PbCurveList.pb',
  package='pbCurveList',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x1fstatic/protoDefs/PbCurveList.pb\x12\x0bpbCurveList\"d\n\x0bPbCurveList\x12\x16\n\x0epointAttrNames\x18\x06 \x03(\t\x12\x16\n\x0e\x63urveAttrNames\x18\x07 \x03(\t\x12%\n\tcurveList\x18\x05 \x03(\x0b\x32\x12.pbCurveList.Curve\"M\n\x05\x43urve\x12\n\n\x02id\x18\x04 \x02(\r\x12%\n\tpointList\x18\x03 \x03(\x0b\x32\x12.pbCurveList.Point\x12\x11\n\tvalueList\x18\x02 \x03(\x02\"\x1a\n\x05Point\x12\x11\n\tvalueList\x18\x01 \x03(\x02'
)




_PBCURVELIST = _descriptor.Descriptor(
  name='PbCurveList',
  full_name='pbCurveList.PbCurveList',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pointAttrNames', full_name='pbCurveList.PbCurveList.pointAttrNames', index=0,
      number=6, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='curveAttrNames', full_name='pbCurveList.PbCurveList.curveAttrNames', index=1,
      number=7, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='curveList', full_name='pbCurveList.PbCurveList.curveList', index=2,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=148,
)


_CURVE = _descriptor.Descriptor(
  name='Curve',
  full_name='pbCurveList.Curve',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='pbCurveList.Curve.id', index=0,
      number=4, type=13, cpp_type=3, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pointList', full_name='pbCurveList.Curve.pointList', index=1,
      number=3, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='valueList', full_name='pbCurveList.Curve.valueList', index=2,
      number=2, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=150,
  serialized_end=227,
)


_POINT = _descriptor.Descriptor(
  name='Point',
  full_name='pbCurveList.Point',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='valueList', full_name='pbCurveList.Point.valueList', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=229,
  serialized_end=255,
)

_PBCURVELIST.fields_by_name['curveList'].message_type = _CURVE
_CURVE.fields_by_name['pointList'].message_type = _POINT
DESCRIPTOR.message_types_by_name['PbCurveList'] = _PBCURVELIST
DESCRIPTOR.message_types_by_name['Curve'] = _CURVE
DESCRIPTOR.message_types_by_name['Point'] = _POINT
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

PbCurveList = _reflection.GeneratedProtocolMessageType('PbCurveList', (_message.Message,), {
  'DESCRIPTOR' : _PBCURVELIST,
  '__module__' : 'static.protoDefs.PbCurveList.pb_pb2'
  # @@protoc_insertion_point(class_scope:pbCurveList.PbCurveList)
  })
_sym_db.RegisterMessage(PbCurveList)

Curve = _reflection.GeneratedProtocolMessageType('Curve', (_message.Message,), {
  'DESCRIPTOR' : _CURVE,
  '__module__' : 'static.protoDefs.PbCurveList.pb_pb2'
  # @@protoc_insertion_point(class_scope:pbCurveList.Curve)
  })
_sym_db.RegisterMessage(Curve)

Point = _reflection.GeneratedProtocolMessageType('Point', (_message.Message,), {
  'DESCRIPTOR' : _POINT,
  '__module__' : 'static.protoDefs.PbCurveList.pb_pb2'
  # @@protoc_insertion_point(class_scope:pbCurveList.Point)
  })
_sym_db.RegisterMessage(Point)


# @@protoc_insertion_point(module_scope)
